# Generated by Django 5.2.3 on 2025-07-24 15:29

import djangocms_text.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_notifications", "0006_alter_emailnotification_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailnotification",
            name="body_html",
            field=djangocms_text.fields.HTMLField(
                blank=True,
                help_text="used when rendering the email in html.",
                verbose_name="email body (html)",
            ),
        ),
    ]
