# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aldryn_forms', '0011_auto_20180110_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValidationFormSubmission',
            fields=[
                ('formsubmission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aldryn_forms.FormSubmission')),
                ('is_valid', models.BooleanField(default=False, verbose_name='is valid')),
            ],
            bases=('aldryn_forms.formsubmission',),
        ),
        migrations.CreateModel(
            name='EmailValidationFormPlugin',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('aldryn_forms.formplugin',),
        ),
    ]
