# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailvalidationformsubmission',
            options={'verbose_name': 'Form submission with validated email', 'verbose_name_plural': 'Form submissions with validated email'},
        ),
    ]
