# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation', '0002_auto_20180222_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidateddEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_validation.EmailValidationFormSubmission')),
            ],
            options={
                'verbose_name': 'Validated email',
                'verbose_name_plural': 'Validated emails',
            },
        ),
    ]
