# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-10 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation', '0003_validateddemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValidateddEmail',
            new_name='ValidatedEmail',
        ),
    ]
