# Generated by Django 3.2.8 on 2021-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0013_add_field_is_enable_autofill_from_url_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formplugin',
            name='action_backend',
            field=models.CharField(choices=[('none', 'None'), ('email_only_orig', 'Email only'), ('email_only', 'Email uniquement (avec détection de robot)'), ('default_orig', 'Default'), ('default', 'Par défaut (avec détection de robot)')], default='default', max_length=15, verbose_name='Action backend'),
        ),
    ]
