# Generated by Django 4.2.5 on 2023-10-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_forms", "0014_alter_emailfieldplugin_cmsplugin_ptr_and_more"),
        ("aldryn_forms", "0014_alter_formplugin_action_backend"),
    ]

    operations = []
